// HUB의 모든 화면에서 공유하는 서비스 데이터입니다. 서비스가 늘어나도 한 곳만 수정하면 됩니다.
export const services = [
  {id:"openai",name:"OpenAI API",category:"AI 모델",icon:"/illustrations/service-openai.svg",url:"https://platform.openai.com/",free:false,price:"중간",difficulty:"쉬움",api:true,features:{text:true,image:true,video:false,voice:true,search:false},bestFor:"챗봇·콘텐츠·멀티모달",strengths:["범용성이 높음","여러 AI 기능을 한 곳에서 구성"],caveat:"사용량에 따라 비용이 달라질 수 있음",tags:["텍스트","이미지","음성","멀티모달"],uses:["chat","image","voice","shorts","api"]},
  {id:"gemini",name:"Google Gemini API",category:"AI 모델",icon:"/illustrations/service-gemini.svg",url:"https://ai.google.dev/",free:true,price:"저렴",difficulty:"쉬움",api:true,features:{text:true,image:true,video:true,voice:false,search:true},bestFor:"텍스트·이미지·멀티모달",strengths:["멀티모달 활용","Google AI 생태계 연계"],caveat:"모델별 지원 기능과 한도 확인 필요",tags:["텍스트","이미지","멀티모달"],uses:["chat","image","video","shorts","api"]},
  {id:"claude",name:"Claude API",category:"AI 모델",icon:"/illustrations/service-claude.svg",url:"https://www.anthropic.com/api",free:false,price:"중간",difficulty:"쉬움",api:true,features:{text:true,image:false,video:false,voice:false,search:false},bestFor:"문서·분석·코딩",strengths:["텍스트 중심 작업","긴 문서 처리에 활용"],caveat:"생성형 미디어 목적에는 다른 선택지가 유리",tags:["텍스트","코딩","분석"],uses:["chat","api"]},
  {id:"groq",name:"Groq",category:"AI 추론 API",icon:"/illustrations/service-groq.svg",url:"https://groq.com/",free:true,price:"저렴",difficulty:"쉬움",api:true,features:{text:true,image:false,video:false,voice:false,search:false},bestFor:"빠른 AI 앱·챗봇",strengths:["빠른 추론을 목표로 함","API 방식으로 연결"],caveat:"지원 모델 범위를 확인해야 함",tags:["빠른 응답","LLM","API"],uses:["chat","api"]},
  {id:"replicate",name:"Replicate",category:"AI 모델 실행",icon:"/illustrations/service-replicate.svg",url:"https://replicate.com/",free:true,price:"중간",difficulty:"보통",api:true,features:{text:false,image:true,video:true,voice:false,search:false},bestFor:"이미지·영상 생성",strengths:["다양한 모델 선택","생성형 미디어 실험에 적합"],caveat:"모델별 비용과 사용 조건이 다름",tags:["이미지","영상","오픈 모델"],uses:["shorts","image","video","api"]},
  {id:"fal",name:"fal",category:"생성형 미디어 API",icon:"/illustrations/service-fal.svg",url:"https://fal.ai/",free:true,price:"중간",difficulty:"보통",api:true,features:{text:false,image:true,video:true,voice:true,search:false},bestFor:"생성 이미지·영상·음성 앱",strengths:["생성형 미디어 모델 활용","개발자용 API 제공"],caveat:"모델별 가격과 지원 기능 확인 필요",tags:["이미지","영상","음성"],uses:["shorts","image","video","voice","api"]},
  {id:"elevenlabs",name:"ElevenLabs",category:"AI 음성",icon:"/illustrations/service-elevenlabs.svg",url:"https://elevenlabs.io/",free:true,price:"중간",difficulty:"쉬움",api:true,features:{text:false,image:false,video:false,voice:true,search:false},bestFor:"TTS·더빙·음성 콘텐츠",strengths:["음성 콘텐츠 제작","더빙·TTS 활용"],caveat:"음성 기능 중심 서비스",tags:["음성","더빙","TTS"],uses:["voice","shorts"]},
  {id:"firecrawl",name:"Firecrawl",category:"웹 데이터 API",icon:"/illustrations/service-firecrawl.svg",url:"https://www.firecrawl.dev/",free:true,price:"중간",difficulty:"보통",api:true,features:{text:true,image:false,video:false,voice:false,search:true},bestFor:"웹 검색·데이터 수집",strengths:["웹 데이터 파이프라인","AI 앱에 웹 콘텐츠 연결"],caveat:"대규모 수집은 사용량 관리 필요",tags:["검색","크롤링","데이터"],uses:["api","chat"]},
  {id:"runpod",name:"Runpod",category:"AI 인프라",icon:"/illustrations/service-runpod.svg",url:"https://www.runpod.io/",free:false,price:"중간",difficulty:"어려움",api:true,features:{text:false,image:true,video:true,voice:false,search:false},bestFor:"GPU 작업·AI 인프라",strengths:["GPU 컴퓨팅","AI 개발 인프라 구성"],caveat:"개발 지식이 필요할 수 있음",tags:["GPU","클라우드","AI"],uses:["api","image","video"]},
  {id:"huggingface",name:"Hugging Face",category:"AI 모델·플랫폼",icon:"/illustrations/service-huggingface.svg",url:"https://huggingface.co/",free:true,price:"저렴",difficulty:"보통",api:true,features:{text:true,image:true,video:false,voice:false,search:false},bestFor:"오픈 모델 탐색·실험",strengths:["폭넓은 모델 생태계","모델·데이터셋 탐색"],caveat:"모델별 사용 조건 확인 필요",tags:["오픈 모델","데이터","ML"],uses:["image","chat","api"]},
  {id:"mistral",name:"Mistral AI",category:"AI 모델",icon:"/illustrations/service-mistral.svg",url:"https://mistral.ai/",free:true,price:"저렴",difficulty:"쉬움",api:true,features:{text:true,image:false,video:false,voice:false,search:false},bestFor:"LLM 앱·개발",strengths:["LLM 중심 서비스","개발자용 API 제공"],caveat:"목적에 맞는 모델 선택 필요",tags:["LLM","API","오픈 모델"],uses:["chat","api"]},
  {id:"together",name:"Together AI",category:"AI 인프라·API",icon:"/illustrations/service-together.svg",url:"https://www.together.ai/",free:true,price:"저렴",difficulty:"보통",api:true,features:{text:true,image:true,video:false,voice:false,search:false},bestFor:"오픈 모델 기반 AI 앱",strengths:["오픈 모델 활용","AI 개발 인프라"],caveat:"모델별 비용과 지원 범위 확인 필요",tags:["오픈 모델","GPU","API"],uses:["chat","image","api"]}
];
export const serviceMap=Object.fromEntries(services.map(service=>[service.id,service]));