"use client";

import { useState } from "react";
import Link from "next/link";

// 간단한 CSV와 JSON 배열을 서로 변환하는 브라우저용 도구입니다.
function parseCSV(text) { const rows=[]; let row=[], cell="", quoted=false; for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1]; if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue;} if(c==='"'){quoted=!quoted;continue;} if(c===','&&!quoted){row.push(cell);cell="";continue;} if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);rows.push(row);row=[];cell="";continue;} cell+=c;} if(cell||row.length){row.push(cell);rows.push(row);} return rows; }
function toCSV(data){if(!Array.isArray(data)||!data.length)throw new Error("JSON 배열을 입력하세요."); const keys=[...new Set(data.flatMap(x=>Object.keys(x||{})))]; return [keys.join(","),...data.map(x=>keys.map(k=>`"${String(x?.[k]??"").replace(/"/g,'""')}"`).join(","))].join("\n");}
export default function CsvJsonPage(){const [mode,setMode]=useState("csv");const [input,setInput]=useState("");const [out,setOut]=useState("");const [error,setError]=useState("");const convert=()=>{try{if(mode==="csv"){const rows=parseCSV(input);if(rows.length<2)throw new Error("헤더와 데이터가 포함된 CSV를 입력하세요.");const h=rows[0];setOut(JSON.stringify(rows.slice(1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??""]))),null,2));}else{setOut(toCSV(JSON.parse(input)));}setError("");}catch(e){setError(e.message||"변환에 실패했습니다.");}};return <main className="page toolPage"><header className="header"><Link className="logo" href="/">HUB</Link><nav><Link href="/tools">도구 모음</Link><Link href="/">서비스 찾기</Link></nav></header><section className="guideHero"><div className="eyebrow">CSV ↔ JSON</div><h1>CSV · JSON<br/><span>빠른 변환기</span></h1><p>표 형태의 데이터를 API용 JSON으로, JSON 배열을 CSV로 변환합니다.</p></section><section className="section"><div className="toolPanel"><div className="toolActions"><button className={mode==="csv"?"active":""} onClick={()=>{setMode("csv");setOut("")}}>CSV → JSON</button><button className={mode==="json"?"active":""} onClick={()=>{setMode("json");setOut("")}}>JSON → CSV</button></div><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={mode==="csv"?"name,age\nKim,33\nLee,29":"[{\"name\":\"Kim\",\"age\":33}]"}/><div className="toolActions"><button onClick={convert}>변환하기</button><button onClick={()=>{setInput("");setOut("");setError("")}}>초기화</button></div>{error&&<p className="toolError">{error}</p>}<div className="toolResult"><small>결과</small><pre>{out||"여기에 변환 결과가 표시됩니다."}</pre></div><p className="toolNote">브라우저에서 처리됩니다. 복잡한 CSV의 특수 형식은 별도 검증이 필요할 수 있습니다.</p></div></section></main>}
